#!/bin/sh
set -Eeuo pipefail

echo "Running pre-commit hook..."
echo

echo "Formatting and linting staged files..."
lint-staged
echo

echo "Checking for available updates..."
echo "Checking base project..."
ncu
echo

echo "Checking client project..."
ncu --cwd client
echo
